name: Pytorch MPS test

on:
  workflow_dispatch:

jobs:
  macos-matrix:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-26, macos-15, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3

      - name: Create Python environment
        shell: bash -l {0}
        run: |
          conda create -y -n env_pytorch python=3.9 --yes
          conda activate env_pytorch
          conda install pytorch torchvision torchaudio -c pytorch-nightly --yes

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate env_pytorch
          PYTORCH_DEBUG_MPS_ALLOCATOR=1 python test.py
          PYTORCH_DEBUG_MPS_ALLOCATOR=1 python test2.py
