name: Pytorch MPS test

on:
  workflow_dispatch:

jobs:
  macos-matrix:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
#        runner: [macos-26, macos-15, macos-14]
        runner: [macos-26]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh && sh Miniconda3-latest-MacOSX-arm64.sh -b
      - run: |
          conda create --name env_pytorch --yes python=3.9
      - run: |
          conda activate env_pytorch
      - run: |
          conda install pytorch torchvision torchaudio -c pytorch-nightly --yes
      - run: |
          PYTORCH_DEBUG_MPS_ALLOCATOR=1 python3 test.py
      - run: |
          PYTORCH_DEBUG_MPS_ALLOCATOR=1 python3 test2.py
